spring.application.name=tictactoe
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
spring.security.user.password=${ADMIN_USERNAME}
spring.security.user.name=${ADMIN_PASSWORD}
jwt.access.secret=${JWT_ACCESS_SECRET}
jwt.refresh.secret=${JWT_REFRESH_SECRET}
jwt.access.duration=30m
jwt.refresh.duration=1d


